In [1]:
import pandas as pd
import numpy as np

Collecting data for Developing Remcomendation model ,


This is a movies recommending model so here i taking movies data set from kaggle

In [2]:
movie_data=pd.read_csv(r"C:\Users\MANEESH\OneDrive\Desktop\Recomendation system\New folder\tmdb_5000_movies.csv")

credit_data=pd.read_csv(r"C:\Users\MANEESH\OneDrive\Desktop\Recomendation system\New folder\tmdb_5000_credits.csv")

In [3]:
movie_data.head(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466

In [4]:
movie_data.shape

(4803, 20)

In [5]:
credit_data.head(3)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [6]:
credit_data.shape

(4803, 4)

In [7]:
type(credit_data)

pandas.core.frame.DataFrame

In [8]:
#here we need to merge these two data set so we have to rename column movie_id to id in credit data 
# because this fields gives same information from both data sets

credit_data.rename(columns = {"movie_id": "id"}, 
          inplace = True)

In [9]:
credit_data.head()

,id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [10]:
#merging the two dataframe on id column

data=pd.merge(movie_data,credit_data, on = "id", how = "inner")

In [11]:
data

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title_x,vote_average,vote_count,title_y,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,El Mariachi,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,Newlyweds,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,"Signed, Sealed, Delivered","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,Shanghai Calling,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,My Date with Drew,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [12]:
data_copy=data

In [13]:
data_copy

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title_x,vote_average,vote_count,title_y,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,El Mariachi,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,Newlyweds,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,"Signed, Sealed, Delivered","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,Shanghai Calling,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,My Date with Drew,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [14]:
data.shape

(4803, 23)

In [15]:
data.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title_x', 'vote_average',
       'vote_count', 'title_y', 'cast', 'crew'],
      dtype='object')

Here i developing a content based recommendation system,


###### content based recommendation system

A Recommender System, that provides recommendations to the user based on the item similarity format is known as a Content-Based Recommender System. So in broader terms, this type of recommender system recommends products that are similar to the products that are already liked or viewed by the users.

So here we do not need all the features in the data set ,we have to select features which gives more content about the moves

In [16]:
#final data for preprocessing,
#creating a  function to select features which are more important for developing our model

def finaldata(feature):
    for col in data.columns:
        if not col in feature:
            data.drop(col,axis=1,inplace=True)

In [17]:
finaldata(data[['genres','id','keywords','original_title','overview','tagline','cast', 'crew']])

In [18]:
data

,genres,id,keywords,original_title,overview,tagline,cast,crew
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A cryptic message from Bond’s past sends him o...,A Plan No One Escapes,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,Following the death of District Attorney Harve...,The Legend Ends,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"John Carter is a war-weary, former military ca...","Lost in our world, found in another.","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...
4798,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",El Mariachi,El Mariachi just wants to play his guitar and ...,"He didn't come looking for trouble, but troubl...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",72766,[],Newlyweds,A newlywed couple's honeymoon is upended by th...,A newlywed couple's honeymoon is upended by th...,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",NaN,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,[],126186,[],Shanghai Calling,When ambitious New York attorney Sam is sent t...,A New Yorker in Shanghai,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,"[{""id"": 99, ""name"": ""Documentary""}]",25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",My Date with Drew,Ever since the second grade when he first saw ...,NaN,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4803 entries, 0 to 4802
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   genres          4803 non-null   object
 1   id              4803 non-null   int64
 2   keywords        4803 non-null   object
 3   original_title  4803 non-null   object
 4   overview        4800 non-null   object
 5   tagline         3959 non-null   object
 6   cast            4803 non-null   object
 7   crew            4803 non-null   object
dtypes: int64(1), object(7)
memory usage: 337.7+ KB

In [20]:
data.genres[0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [21]:
type(data.genres)

pandas.core.series.Series

In [22]:
data.isnull().sum()

genres              0
id                  0
keywords            0
original_title      0
overview            3
tagline           844
cast                0
crew                0
dtype: int64

In [23]:
data.drop('tagline',axis=1,inplace=True)

In [24]:
data

,genres,id,keywords,original_title,overview,cast,crew
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4798,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",El Mariachi,El Mariachi just wants to play his guitar and ...,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",72766,[],Newlyweds,A newlywed couple's honeymoon is upended by th...,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,[],126186,[],Shanghai Calling,When ambitious New York attorney Sam is sent t...,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,"[{""id"": 99, ""name"": ""Documentary""}]",25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",My Date with Drew,Ever since the second grade when he first saw ...,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [25]:
#drop all the null values

data.dropna(inplace=True)

In [26]:
data.isnull().sum()

genres            0
id                0
keywords          0
original_title    0
overview          0
cast              0
crew              0
dtype: int64

In [27]:
import ast

In [28]:
#fetching information 

def fetch_info(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L

In [29]:
data['genres'] = data['genres'].apply(fetch_info)

data['keywords'] = data['keywords'].apply(fetch_info)

data['cast'] = data['cast'].apply(fetch_info)

data.head()

,genres,id,keywords,original_title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [30]:
#fetching first 5 actors name from cast feature

data['cast']=data['cast'].apply(lambda actor : actor[0:5])

In [31]:
data.cast[0]

['Sam Worthington',
 'Zoe Saldana',
 'Sigourney Weaver',
 'Stephen Lang',
 'Michelle Rodriguez']

In [32]:
data.crew[0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [33]:
#fetching director name of each movies from crew 

def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [34]:
data['crew'] = data['crew'].apply(fetch_director)

In [35]:
data['crew']

0                                [James Cameron]
1                               [Gore Verbinski]
2                                   [Sam Mendes]
3                            [Christopher Nolan]
4                               [Andrew Stanton]
                          ...
4798                          [Robert Rodriguez]
4799                              [Edward Burns]
4800                               [Scott Smith]
4801                               [Daniel Hsia]
4802    [Brian Herzlinger, Jon Gunn, Brett Winn]
Name: crew, Length: 4800, dtype: object

In [35]:
data.head()

,genres,id,keywords,original_title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [36]:
data.crew[0]

['James Cameron']

In [36]:
# remove spaces because if we got one movie director is  James Cameron and the other movie by James James Cromwell,in this case 
#our recommendation will go wrong 
def space_rem(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [37]:
data['cast'] = data['cast'].apply(space_rem)
data['crew'] = data['crew'].apply(space_rem)
data['genres'] = data['genres'].apply(space_rem)
data['keywords'] = data['keywords'].apply(space_rem)

In [38]:
data.crew[0]

['JamesCameron']

In [39]:
data.overview[0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [40]:
data['overview'] = data['overview'].apply(lambda x:x.split())

In [41]:
data.overview[0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.']

In [42]:
# aggrigating all the information into a single columns for getting content
data['content'] = data['overview'] + data['genres'] + data['keywords'] + data['cast'] + data['crew']

In [43]:
data.head()

,genres,id,keywords,original_title,overview,cast,crew,content
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,"[Action, Adventure, Crime]",206647,"[spy, basedonnovel, secretagent, sequel, mi6, ...",Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,"[Action, Crime, Drama, Thriller]",49026,"[dccomics, crimefighter, terrorist, secretiden...",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,"[Action, Adventure, ScienceFiction]",49529,"[basedonnovel, mars, medallion, spacetravel, p...",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [45]:
#Remove all the unwanted columns
final_data = data.drop(columns=['overview','genres','keywords','cast','crew'])

In [46]:
final_data

,id,original_title,content
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4798,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4799,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4800,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4801,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4802,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [47]:
final_data['content'] = final_data['content'].apply(lambda x: " ".join(x))

In [48]:
final_data.sample(3)

,id,original_title,content
3129,283671,Jungle Shuffle,In this turbulent jungle adventure an outcast ...
4419,272724,Doc Holliday's Revenge,"In 1882, Joseph and Elizabeth Cooley head West..."
1987,4935,ハウルの動く城,"When Sophie, a shy young woman, is cursed with..."

In [49]:
# here i used NLP for vectorizing words
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [50]:
vector = cv.fit_transform(final_data['content']).toarray()

In [51]:
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [52]:
vector.shape

(4800, 5000)

In [52]:
# cosine similarity is used to find the similarity between each movie
from sklearn.metrics.pairwise import cosine_similarity

In [53]:
similarity = cosine_similarity(vector)

In [54]:
similarity

array([[1.        , 0.08458258, 0.05812382, ..., 0.02478408, 0.02739983,
        0.        ],
       [0.08458258, 1.        , 0.06063391, ..., 0.02585438, 0.        ,
        0.        ],
       [0.05812382, 0.06063391, 1.        , ..., 0.02665009, 0.        ,
        0.        ],
       ...,
       [0.02478408, 0.02585438, 0.02665009, ..., 1.        , 0.07537784,
        0.04828045],
       [0.02739983, 0.        , 0.        , ..., 0.07537784, 1.        ,
        0.05337605],
       [0.        , 0.        , 0.        , ..., 0.04828045, 0.05337605,
        1.        ]])

In [55]:
final_data[final_data['original_title'] == 'The Lego Movie'].index[0]

744

In [62]:
def recommend(movie):
    index = final_data[final_data['original_title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(final_data.iloc[i[0]].original_title)

In [64]:
recommend('Avatar')

Titan A.E.
Independence Day
Aliens vs Predator: Requiem
Small Soldiers
Battle: Los Angeles

In [65]:
import pickle

In [66]:
pickle.dump(final_data,open('movie_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))

In [67]:
 pickle.dump(final_data.to_dict(),open('movie_listdict.pkl','wb'))

In [68]:
movie_data=pickle.load(open('movie_listdict.pkl','rb'))
movies=pd.DataFrame(movie_data)#dataframe

In [69]:
movies

,id,original_title,content
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."
...,...,...,...
4798,9367,El Mariachi,El Mariachi just wants to play his guitar and ...
4799,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...
4800,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic..."
4801,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...
4802,25975,My Date with Drew,Ever since the second grade when he first saw ...

In [70]:
final_data.head()

,id,original_title,content
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [71]:
list(final_data['original_title'].values)

['Avatar',
 "Pirates of the Caribbean: At World's End",
 'Spectre',
 'The Dark Knight Rises',
 'John Carter',
 'Spider-Man 3',
 'Tangled',
 'Avengers: Age of Ultron',
 'Harry Potter and the Half-Blood Prince',
 'Batman v Superman: Dawn of Justice',
 'Superman Returns',
 'Quantum of Solace',
 "Pirates of the Caribbean: Dead Man's Chest",
 'The Lone Ranger',
 'Man of Steel',
 'The Chronicles of Narnia: Prince Caspian',
 'The Avengers',
 'Pirates of the Caribbean: On Stranger Tides',
 'Men in Black 3',
 'The Hobbit: The Battle of the Five Armies',
 'The Amazing Spider-Man',
 'Robin Hood',
 'The Hobbit: The Desolation of Smaug',
 'The Golden Compass',
 'King Kong',
 'Titanic',
 'Captain America: Civil War',
 'Battleship',
 'Jurassic World',
 'Skyfall',
 'Spider-Man 2',
 'Iron Man 3',
 'Alice in Wonderland',
 'X-Men: The Last Stand',
 'Monsters University',
 'Transformers: Revenge of the Fallen',
 'Transformers: Age of Extinction',
 'Oz: The Great and Powerful',
 'The Amazing Spider-Man 2',
 'TRON: Legacy',
 'Cars 2',
 'Green Lantern',
 'Toy Story 3',
 'Terminator Salvation',
 'Furious 7',
 'World War Z',
 'X-Men: Days of Future Past',
 'Star Trek Into Darkness',
 'Jack the Giant Slayer',
 'The Great Gatsby',
 'Prince of Persia: The Sands of Time',
 'Pacific Rim',
 'Transformers: Dark of the Moon',
 'Indiana Jones and the Kingdom of the Crystal Skull',
 'The Good Dinosaur',
 'Brave',
 'Star Trek Beyond',
 'WALL·E',
 'Rush Hour 3',
 '2012',
 'A Christmas Carol',
 'Jupiter Ascending',
 'The Legend of Tarzan',
 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe',
 'X-Men: Apocalypse',
 'The Dark Knight',
 'Up',
 'Monsters vs Aliens',
 'Iron Man',
 'Hugo',
 'Wild Wild West',
 'The Mummy: Tomb of the Dragon Emperor',
 'Suicide Squad',
 'Evan Almighty',
 'Edge of Tomorrow',
 'Waterworld',
 'G.I. Joe: The Rise of Cobra',
 'Inside Out',
 'The Jungle Book',
 'Iron Man 2',
 'Snow White and the Huntsman',
 'Maleficent',
 'Dawn of the Planet of the Apes',
 'The Lovers',
 '47 Ronin',
 'Captain America: The Winter Soldier',
 'Shrek Forever After',
 'Tomorrowland',
 'Big Hero 6',
 'Wreck-It Ralph',
 'The Polar Express',
 'Independence Day: Resurgence',
 'How to Train Your Dragon',
 'Terminator 3: Rise of the Machines',
 'Guardians of the Galaxy',
 'Interstellar',
 'Inception',
 'シン・ゴジラ',
 'The Hobbit: An Unexpected Journey',
 'The Fast and the Furious',
 'The Curious Case of Benjamin Button',
 'X-Men: First Class',
 'The Hunger Games: Mockingjay - Part 2',
 "The Sorcerer's Apprentice",
 'Poseidon',
 'Alice Through the Looking Glass',
 'Shrek the Third',
 'Warcraft',
 'Terminator Genisys',
 'The Chronicles of Narnia: The Voyage of the Dawn Treader',
 'Pearl Harbor',
 'Transformers',
 'Alexander',
 'Harry Potter and the Order of the Phoenix',
 'Harry Potter and the Goblet of Fire',
 'Hancock',
 'I Am Legend',
 'Charlie and the Chocolate Factory',
 'Ratatouille',
 'Batman Begins',
 'Madagascar: Escape 2 Africa',
 'Night at the Museum: Battle of the Smithsonian',
 'X-Men Origins: Wolverine',
 'The Matrix Revolutions',
 'Frozen',
 'The Matrix Reloaded',
 'Thor: The Dark World',
 'Mad Max: Fury Road',
 'Angels & Demons',
 'Thor',
 'Bolt',
 'G-Force',
 'Wrath of the Titans',
 'Dark Shadows',
 'Mission: Impossible - Rogue Nation',
 'The Wolfman',
 'Bee Movie',
 'Kung Fu Panda 2',
 'The Last Airbender',
 'Mission: Impossible III',
 'White House Down',
 'Mars Needs Moms',
 'Flushed Away',
 'Pan',
 'Mr. Peabody & Sherman',
 'Troy',
 "Madagascar 3: Europe's Most Wanted",
 'Die Another Day',
 'Ghostbusters',
 'Armageddon',
 'Men in Black II',
 'Beowulf',
 'Kung Fu Panda 3',
 'Mission: Impossible - Ghost Protocol',
 'Rise of the Guardians',
 'Fun with Dick and Jane',
 'The Last Samurai',
 'Exodus: Gods and Kings',
 'Star Trek',
 'Spider-Man',
 'How to Train Your Dragon 2',
 'Gods of Egypt',
 'Stealth',
 'Watchmen',
 'Lethal Weapon 4',
 'Hulk',
 'G.I. Joe: Retaliation',
 'Sahara',
 'Final Fantasy: The Spirits Within',
 'Captain America: The First Avenger',
 'The World Is Not Enough',
 'Master and Commander: The Far Side of the World',
 'The Twilight Saga: Breaking Dawn - Part 2',
 'Happy Feet Two',
 'The Incredible Hulk',
 'The BFG',
 'The Revenant',
 'Turbo',
 'Rango',
 'Penguins of Madagascar',
 'The Bourne Ultimatum',
 'Kung Fu Panda',
 'Ant-Man',
 'The Hunger Games: Catching Fire',
 'Home',
 'War of the Worlds',
 'Bad Boys II',
 'Puss in Boots',
 'Salt',
 'Noah',
 'The Adventures of Tintin',
 'Harry Potter and the Prisoner of Azkaban',
 'Australia',
 'After Earth',
 'Dinosaur',
 'Night at the Museum: Secret of the Tomb',
 'Megamind',
 "Harry Potter and the Philosopher's Stone",
 'R.I.P.D.',
 'Pirates of the Caribbean: The Curse of the Black Pearl',
 'The Hunger Games: Mockingjay - Part 1',
 'The Da Vinci Code',
 'Rio 2',
 'X2',
 'Fast Five',
 'Sherlock Holmes: A Game of Shadows',
 'Clash of the Titans',
 'Total Recall',
 'The 13th Warrior',
 'The Bourne Legacy',
 'Batman & Robin',
 'How the Grinch Stole Christmas',
 'The Day After Tomorrow',
 'Mission: Impossible II',
 'The Perfect Storm',
 '4: Rise of the Silver Surfer',
 'Life of Pi',
 'Ghost Rider',
 'Jason Bourne',
 "Charlie's Angels: Full Throttle",
 'Prometheus',
 'Stuart Little 2',
 'Elysium',
 'The Chronicles of Riddick',
 'RoboCop',
 'Speed Racer',
 'How Do You Know',
 'Knight and Day',
 'Oblivion',
 'Star Wars: Episode III - Revenge of the Sith',
 'Star Wars: Episode II - Attack of the Clones',
 'Monsters, Inc.',
 'The Wolverine',
 'Star Wars: Episode I - The Phantom Menace',
 'The Croods',
 'Astérix aux Jeux Olympiques',
 'Windtalkers',
 "The Huntsman: Winter's War",
 'Teenage Mutant Ninja Turtles',
 'Gravity',
 "Dante's Peak",
 'Teenage Mutant Ninja Turtles: Out of the Shadows',
 'Fantastic Four',
 'Night at the Museum',
 'San Andreas',
 'Tomorrow Never Dies',
 'The Patriot',
 "Ocean's Twelve",
 'Mr. & Mrs. Smith',
 'Insurgent',
 'The Aviator',
 "Gulliver's Travels",
 'The Green Hornet',
 '300: Rise of an Empire',
 'The Smurfs',
 'Home on the Range',
 'Allegiant',
 'Real Steel',
 'The Smurfs 2',
 'Speed 2: Cruise Control',
 "Ender's Game",
 'Live Free or Die Hard',
 'The Lord of the Rings: The Fellowship of the Ring',
 'Around the World in 80 Days',
 'Ali',
 'The Cat in the Hat',
 'I, Robot',
 'Kingdom of Heaven',
 'Stuart Little',
 'The Princess and the Frog',
 'The Martian',
 'The Island',
 'Town & Country',
 'Gone in Sixty Seconds',
 'Gladiator',
 'Minority Report',
 'Harry Potter and the Chamber of Secrets',
 'Casino Royale',
 'Planet of the Apes',
 'Terminator 2: Judgment Day',
 'Public Enemies',
 'American Gangster',
 'True Lies',
 'The Taking of Pelham 1 2 3',
 'Little Fockers',
 'The Other Guys',
 'Eraser',
 'Django Unchained',
 'The Hunchback of Notre Dame',
 "The Emperor's New Groove",
 'The Expendables 2',
 'National Treasure',
 'Eragon',
 'Where the Wild Things Are',
 'Epic',
 'The Tourist',
 'End of Days',
 'Blood Diamond',
 'The Wolf of Wall Street',
 'Batman Forever',
 'Starship Troopers',
 'Cloud Atlas',
 "Legend of the Guardians: The Owls of Ga'Hoole",
 'Catwoman',
 'Hercules',
 'Treasure Planet',
 'Land of the Lost',
 'The Expendables 3',
 'Point Break',
 'Son of the Mask',
 'In the Heart of the Sea',
 'The Adventures of Pluto Nash',
 'Green Zone',
 'The Peanuts Movie',
 'The Spanish Prisoner',
 'The Mummy Returns',
 'Gangs of New York',
 '金陵十三釵',
 "Surf's Up",
 'The Stepford Wives',
 'Black Hawk Down',
 'The Campaign',
 'The Fifth Element',
 'Sex and the City 2',
 'The Road to El Dorado',
 'Ice Age: Continental Drift',
 'Cinderella',
 'The Lovely Bones',
 'Finding Nemo',
 'The Lord of the Rings: The Return of the King',
 'The Lord of the Rings: The Two Towers',
 'Seventh Son',
 'Lara Croft: Tomb Raider',
 'Transcendence',
 'Jurassic Park III',
 'Rise of the Planet of the Apes',
 'The Spiderwick Chronicles',
 'A Good Day to Die Hard',
 'The Alamo',
 'The Incredibles',
 'Cutthroat Island',
 'Percy Jackson & the Olympians: The Lightning Thief',
 'Men in Black',
 'Toy Story 2',
 'Unstoppable',
 'Rush Hour 2',
 'What Lies Beneath',
 'Cloudy with a Chance of Meatballs',
 'Ice Age: Dawn of the Dinosaurs',
 'The Secret Life of Walter Mitty',
 "Charlie's Angels",
 'The Departed',
 'Mulan',
 'Tropic Thunder',
 'The Girl with the Dragon Tattoo',
 'Die Hard: With a Vengeance',
 'Sherlock Holmes',
 'Ben-Hur',
 'Atlantis: The Lost Empire',
 'Alvin and the Chipmunks: The Road Chip',
 'Valkyrie',
 "You Don't Mess with the Zohan",
 'Pixels',
 'A.I. Artificial Intelligence',
 'The Haunted Mansion',
 'Contact',
 'Hollow Man',
 'The Interpreter',
 'Percy Jackson: Sea of Monsters',
 'Lara Croft Tomb Raider: The Cradle of Life',
 'Now You See Me 2',
 'The Saint',
 'Spy Game',
 'Mission to Mars',
 'Rio',
 'Bicentennial Man',
 'Volcano',
 "The Devil's Own",
 'K-19: The Widowmaker',
 'Conan the Barbarian',
 'Cinderella Man',
 'The Nutcracker: The Untold Story',
 'Seabiscuit',
 'Twister',
 'Cast Away',
 'Happy Feet',
 'The Bourne Supremacy',
 'Air Force One',
 "Ocean's Eleven",
 'The Three Musketeers',
 'Hotel Transylvania',
 'Enchanted',
 'Safe House',
 '102 Dalmatians',
 'Tower Heist',
 'The Holiday',
 'Enemy of the State',
 "It's Complicated",
 "Ocean's Thirteen",
 'Open Season',
 'Divergent',
 'Enemy at the Gates',
 'The Rundown',
 'Last Action Hero',
 'Memoirs of a Geisha',
 'The Fast and the Furious: Tokyo Drift',
 'Arthur Christmas',
 'Meet Joe Black',
 'Collateral Damage',
 'All That Jazz',
 'Mirror Mirror',
 'Scott Pilgrim vs. the World',
 'The Core',
 'Nutty Professor II: The Klumps',
 'Scooby-Doo',
 'Dredd',
 'Click',
 'Creepshow',
 'Cats & Dogs 2 : The Revenge of Kitty Galore',
 'Jumper',
 'Hellboy II: The Golden Army',
 'Zodiac',
 'The 6th Day',
 'Bruce Almighty',
 'The Expendables',
 'Mission: Impossible',
 'The Hunger Games',
 'The Hangover Part II',
 'Batman Returns',
 'Over the Hedge',
 'Lilo & Stitch',
 "Charlotte's Web",
 'Deep Impact',
 'RED 2',
 'The Longest Yard',
 'Alvin and the Chipmunks: Chipwrecked',
 'Grown Ups 2',
 'Get Smart',
 "Something's Gotta Give",
 'Shutter Island',
 'Four Christmases',
 'Robots',
 'Face/Off',
 'Bedtime Stories',
 'Road to Perdition',
 'Just Go with It',
 'Con Air',
 'Eagle Eye',
 'Cold Mountain',
 'The Book of Eli',
 'Flubber',
 'The Haunting',
 'Space Jam',
 'The Pink Panther',
 'The Day the Earth Stood Still',
 'Conspiracy Theory',
 'Fury',
 'Six Days Seven Nights',
 'Yogi Bear',
 'Spirit: Stallion of the Cimarron',
 'Zookeeper',
 'Lost in Space',
 'The Manchurian Candidate',
 'Déjà Vu',
 'Hotel Transylvania 2',
 'Fantasia 2000',
 'The Time Machine',
 'Mighty Joe Young',
 'Swordfish',
 'The Legend of Zorro',
 'What Dreams May Come',
 'Little Nicky',
 'The Brothers Grimm',
 'Mars Attacks!',
 'Évolution',
 'The Edge',
 'Surrogates',
 'Thirteen Days',
 'Daylight',
 'Walking With Dinosaurs',
 'Battlefield Earth',
 'Looney Tunes: Back in Action',
 'Nine',
 'Timeline',
 'The Postman',
 'Babe: Pig in the City',
 'The Last Witch Hunter',
 'Red Planet',
 'Arthur et les Minimoys',
 'Oceans',
 'A Sound of Thunder',
 'Pompeii',
 'Don Gato: El inicio de la pandilla',
 'A Beautiful Mind',
 'The Lion King',
 'Journey 2: The Mysterious Island',
 'Cloudy with a Chance of Meatballs 2',
 'Red Dragon',
 'Hidalgo',
 'Jack and Jill',
 '2 Fast 2 Furious',
 'The Little Prince',
 'The Invasion',
 'The Adventures of Rocky & Bullwinkle',
 'The Secret Life of Pets',
 'The League of Extraordinary Gentlemen',
 'Despicable Me 2',
 'Independence Day',
 'The Lost World: Jurassic Park',
 'Madagascar',
 'Children of Men',
 'X-Men',
 'Wanted',
 'The Rock',
 'Ice Age: The Meltdown',
 '50 First Dates',
 'Hairspray',
 'Exorcist: The Beginning',
 'Inspector Gadget',
 'Now You See Me',
 'Grown Ups',
 'The Terminal',
 'Hotel for Dogs',
 'Vertical Limit',
 "Charlie Wilson's War",
 'Shark Tale',
 'Dreamgirls',
 'Be Cool',
 'Munich',
 'Tears of the Sun',
 'Killers',
 'The Man from U.N.C.L.E.',
 'Spanglish',
 'Monster House',
 'Bandits',
 'First Knight',
 'Anna and the King',
 'Immortals',
 'Hostage',
 'Titan A.E.',
 'Hollywood Homicide',
 'Soldier',
 'Carriers',
 'Monkeybone',
 'Flight of the Phoenix',
 'Unbreakable',
 'Minions',
 'Sucker Punch',
 'Snake Eyes',
 'Sphere',
 'The Angry Birds Movie',
 "Fool's Gold",
 'Funny People',
 'The Kingdom',
 'Talladega Nights: The Ballad of Ricky Bobby',
 'Dr. Dolittle 2',
 'Braveheart',
 'Jarhead',
 'The Simpsons Movie',
 'The Majestic',
 'Driven',
 'Deux frères',
 'The Village',
 'Doctor Dolittle',
 'Signs',
 'Shrek 2',
 'Cars',
 'Runaway Bride',
 'xXx',
 'The SpongeBob Movie: Sponge Out of Water',
 'Ransom',
 'Inglourious Basterds',
 'Hook',
 'Die Hard 2',
 'S.W.A.T.',
 'Vanilla Sky',
 'Lady in the Water',
 'AVP: Alien vs. Predator',
 'Alvin and the Chipmunks: The Squeakquel',
 'We Were Soldiers',
 'Olympus Has Fallen',
 'Star Trek: Insurrection',
 'Battle: Los Angeles',
 'Big Fish',
 'Wolf',
 'War Horse',
 'The Monuments Men',
 'The Abyss',
 'Wall Street: Money Never Sleeps',
 'Dracula Untold',
 'The Siege',
 'Stardust',
 'Seven Years in Tibet',
 'The Dilemma',
 'Bad Company',
 'Doom',
 'I Spy',
 'Underworld: Awakening',
 'Rock of Ages',
 "Hart's War",
 'Killer Elite',
 'Rollerball',
 'Ballistic: Ecks vs. Sever',
 'Hard Rain',
 'Osmosis Jones',
 "Legends of Oz: Dorothy's Return",
 'Blackhat',
 'Sky Captain and the World of Tomorrow',
 'Basic Instinct 2',
 'Escape Plan',
 'The Legend of Hercules',
 'The Sum of All Fears',
 'The Twilight Saga: Eclipse',
 'The Score',
 'Despicable Me',
 'Money Train',
 'Ted 2',
 'Agora',
 'Mystery Men',
 'Hall Pass',
 'The Insider',
 'The Finest Hours',
 'Body of Lies',
 'Dinner for Schmucks',
 'Abraham Lincoln: Vampire Hunter',
 'Entrapment',
 'The X Files',
 'The Last Legion',
 'Saving Private Ryan',
 'Need for Speed',
 'What Women Want',
 'Ice Age',
 'Dreamcatcher',
 'Lincoln',
 'The Matrix',
 'Apollo 13',
 'The Santa Clause 2',
 'Les Misérables',
 "You've Got Mail",
 'Step Brothers',
 'The Mask of Zorro',
 'Due Date',
 'Unbroken',
 'Space Cowboys',
 'Cliffhanger',
 'Broken Arrow',
 'The Kid',
 'World Trade Center',
 'Mona Lisa Smile',
 'The Dictator',
 'Eyes Wide Shut',
 'Annie',
 'Focus',
 'This Means War',
 'Blade: Trinity',
 'Red Dawn',
 'Primary Colors',
 'Resident Evil: Retribution',
 'Death Race',
 'The Long Kiss Goodnight',
 'Proof of Life',
 'Zathura: A Space Adventure',
 'Fight Club',
 'We Are Marshall',
 'Hudson Hawk',
 'Lucky Numbers',
 'I, Frankenstein',
 'Oliver Twist',
 'Elektra',
 'Sin City: A Dame to Kill For',
 'Random Hearts',
 'Everest',
 'Perfume: The Story of a Murderer',
 'Austin Powers in Goldmember',
 'Astro Boy',
 'Jurassic Park',
 'Wyatt Earp',
 'Clear and Present Danger',
 '天將雄師',
 'Little Man',
 'U-571',
 'The American President',
 'The Love Guru',
 '3000 Miles to Graceland',
 'The Hateful Eight',
 'Blades of Glory',
 'Hop',
 '300',
 'Meet the Fockers',
 'Marley & Me',
 'The Green Mile',
 'Wild Hogs',
 'Chicken Little',
 'Gone Girl',
 'The Bourne Identity',
 'GoldenEye',
 "The General's Daughter",
 'The Truman Show',
 'The Prince of Egypt',
 'Daddy Day Care',
 '2 Guns',
 'Cats & Dogs',
 'The Italian Job',
 'Two Weeks Notice',
 'Antz',
 'Couples Retreat',
 'Days of Thunder',
 'Cheaper by the Dozen 2',
 'Maze Runner: The Scorch Trials',
 'Eat Pray Love',
 'The Family Man',
 'RED',
 'Any Given Sunday',
 'The Horse Whisperer',
 'Collateral',
 'The Scorpion King',
 'Ladder 49',
 'Jack Reacher',
 'Deep Blue Sea',
 "Michael Jackson's This Is It",
 'Contagion',
 'Kangaroo Jack',
 'Coraline',
 'The Happening',
 'Man on Fire',
 'The Shaggy Dog',
 'Starsky & Hutch',
 'Jingle All the Way',
 'Hellboy',
 'A Civil Action',
 'ParaNorman',
 'The Jackal',
 'Paycheck',
 'Up Close & Personal',
 'The Tale of Despereaux',
 'The Tuxedo',
 'Under Siege 2: Dark Territory',
 'Jack Ryan: Shadow Recruit',
 'Joy',
 'London Has Fallen',
 'Alien: Resurrection',
 'Shooter',
 'The Boxtrolls',
 'Practical Magic',
 'The Lego Movie',
 'Miss Congeniality 2: Armed and Fabulous',
 'Reign of Fire',
 'Gangster Squad',
 'Year One',
 'Invictus',
 'State of Play',
 'Duplicity',
 'My Favorite Martian',
 'The Sentinel',
 'Planet 51',
 'Star Trek: Nemesis',
 'Intolerable Cruelty',
 'Trouble with the Curve',
 'Edge of Darkness',
 'The Relic',
 'Analyze That',
 'Righteous Kill',
 'Mercury Rising',
 'The Soloist',
 'The Legend of Bagger Vance',
 'Almost Famous',
 'Garfield: A Tail of Two Kitties',
 'xXx: State of the Union',
 'Priest',
 'Sinbad: Legend of the Seven Seas',
 'Event Horizon',
 'Dragonfly',
 'The Black Dahlia',
 'Flyboys',
 'The Last Castle',
 'Supernova',
 "Winter's Tale",
 'The Mortal Instruments: City of Bones',
 'Meet Dave',
 'Dark Water',
 'Edtv',
 'Inkheart',
 'The Spirit',
 'Mortdecai',
 'In the Name of the King: A Dungeon Siege Tale',
 'Beyond Borders',
 '西游记之孙悟空三打白骨精',
 'The Great Raid',
 'Deadpool',
 'Holy Man',
 'American Sniper',
 'Goosebumps',
 'Just Like Heaven',
 'The Flintstones in Viva Rock Vegas',
 'Rambo III',
 'Leatherheads',
 'The Ridiculous 6',
 'Did You Hear About the Morgans?',
 'The Internship',
 'Resident Evil: Afterlife',
 'Red Tails',
 "The Devil's Advocate",
 "That's My Boy",
 'DragonHeart',
 'After the Sunset',
 'Ghost Rider: Spirit of Vengeance',
 "Captain Corelli's Mandolin",
 'The Pacifier',
 'Walking Tall',
 'Forrest Gump',
 'Alvin and the Chipmunks',
 'Meet the Parents',
 'Pocahontas',
 'Superman',
 'The Nutty Professor',
 'Hitch',
 'George of the Jungle',
 'American Wedding',
 'Captain Phillips',
 'Date Night',
 'Casper',
 'The Equalizer',
 'Maid in Manhattan',
 'Crimson Tide',
 'The Pursuit of Happyness',
 'Flightplan',
 'Disclosure',
 'City of Angels',
 'Kill Bill: Vol. 1',
 'Bowfinger',
 'Kill Bill: Vol. 2',
 'Tango & Cash',
 'Death Becomes Her',
 'Shanghai Noon',
 'Executive Decision',
 "Mr. Popper's Penguins",
 'The Forbidden Kingdom',
 'Free Birds',
 'Alien³',
 'Evita',
 'Ronin',
 'The Ghost and the Darkness',
 'Paddington',
 'The Watch',
 'The Hunted',
 'Instinct',
 'Stuck on You',
 'Semi-Pro',
 'The Pirates! In an Adventure with Scientists!',
 'Changeling',
 'Chain Reaction',
 'The Fan',
 'The Phantom of the Opera',
 'Elizabeth: The Golden Age',
 'Æon Flux',
 'Gods and Generals',
 'Turbulence',
 'Imagine That',
 'Muppets Most Wanted',
 'Thunderbirds',
 'Burlesque',
 'Un long dimanche de fiançailles',
 'Lolita',
 'D-Tox',
 'Blade II',
 'Seven Pounds',
 'Bullet to the Head',
 'The Godfather: Part III',
 'Elizabethtown',
 'You, Me and Dupree',
 'Superman II',
 'Gigli',
 "All the King's Men",
 'Shaft',
 'Anastasia',
 'Moulin Rouge!',
 'Domestic Disturbance',
 'Black Mass',
 'Flags of Our Fathers',
 'Law Abiding Citizen',
 'Grindhouse',
 'Beloved',
 'Lucky You',
 'Catch Me If You Can',
 'Zero Dark Thirty',
 'The Break-Up',
 'Mamma Mia!',
 "Valentine's Day",
 'The Dukes of Hazzard',
 'The Thin Red Line',
 'The Change-Up',
 'Man on the Moon',
 'Casino',
 'From Paris with Love',
 'Bulletproof Monk',
 'Me, Myself & Irene',
 'Barnyard',
 'Deck the Halls',
 'The Twilight Saga: New Moon',
 'Shrek',
 'The Adjustment Bureau',
 'Robin Hood: Prince of Thieves',
 'Jerry Maguire',
 'Ted',
 'As Good as It Gets',
 'Patch Adams',
 'Anchorman 2: The Legend Continues',
 'Mr. Deeds',
 'Super 8',
 'Erin Brockovich',
 'How to Lose a Guy in 10 Days',
 '22 Jump Street',
 'Interview with the Vampire',
 'Yes Man',
 'Central Intelligence',
 'Stepmom',
 "Daddy's Home",
 'Into the Woods',
 'Inside Man',
 'Payback',
 'Congo',
 'We Bought a Zoo',
 'Knowing',
 'Failure to Launch',
 'The Ring Two',
 'Crazy, Stupid, Love.',
 'Garfield',
 'Christmas with the Kranks',
 'Moneyball',
 'Outbreak',
 'Non-Stop',
 'Race to Witch Mountain',
 'V for Vendetta',
 'Shanghai Knights',
 'Curious George',
 'Herbie Fully Loaded',
 "Don't Say a Word",
 'Hansel & Gretel: Witch Hunters',
 'Unfaithful',
 'I Am Number Four',
 'Syriana',
 '13 Hours: The Secret Soldiers of Benghazi',
 'The Book of Life',
 'Firewall',
 'Absolute Power',
 'G.I. Jane',
 'The Game',
 'Silent Hill',
 'The Replacements',
 'American Reunion',
 'The Negotiator',
 'Into the Storm',
 'Beverly Hills Cop III',
 'Gremlins 2: The New Batch',

In [72]:
type(final_data)

pandas.core.frame.DataFrame

In [73]:
final_data.to_csv('data.csv') #Saving the final_data to a csv file

In [75]:
data_copy.head(2)

,genres,id,keywords,original_title,overview,cast,crew,content
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."

In [14]:
data_copy[['popularity','original_title']]

      popularity                            original_title
0     150.437577                                    Avatar
1     139.082615  Pirates of the Caribbean: At World's End
2     107.376788                                   Spectre
3     112.312950                     The Dark Knight Rises
4      43.926995                               John Carter
...          ...                                       ...
4798   14.269792                               El Mariachi
4799    0.642552                                 Newlyweds
4800    1.444476                 Signed, Sealed, Delivered
4801    0.857008                          Shanghai Calling
4802    1.929883                         My Date with Drew

[4803 rows x 2 columns]

In [13]:
data_copy[data_copy['popularity']==875.581305]

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title_x,vote_average,vote_count,title_y,cast,crew
546,74000000,"[{""id"": 10751, ""name"": ""Family""}, {""id"": 16, ""...",http://www.minionsmovie.com/,211672,"[{""id"": 3487, ""name"": ""assistant""}, {""id"": 179...",en,Minions,"Minions Stuart, Kevin and Bob are recruited by...",875.581305,"[{""name"": ""Universal Pictures"", ""id"": 33}, {""n...",...,91.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Before Gru, they had a history of bad bosses",Minions,6.4,4571,Minions,"[{""cast_id"": 22, ""character"": ""Scarlet Overkil...","[{""credit_id"": ""5431b2b10e0a2656e20026c7"", ""de..."

#####  Sorting original_title based on popularity for finding top popular movies

In [14]:
data_pop=data_copy.sort_values(by=['popularity','original_title'],ascending=False).head(7)

In [15]:
data_pop[['popularity','original_title']].head(7)

     popularity                                     original_title
546  875.581305                                            Minions
95   724.247784                                       Interstellar
788  514.569956                                           Deadpool
94   481.098624                            Guardians of the Galaxy
127  434.278564                                 Mad Max: Fury Road
28   418.708552                                     Jurassic World
199  271.972889  Pirates of the Caribbean: The Curse of the Bla...